<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGonVTGN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGonVTGN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGonVTGN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGonVTGN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGonVTGN\App_KernelDevDebugContainer([
    'container.build_hash' => 'GonVTGN',
    'container.build_id' => '91c20dd1',
    'container.build_time' => 1704208255,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGonVTGN');
